meta_product_name: "The Coco Network"
meta_title: "The Coco Network - A place for Blythe dolls"
meta_description: "Customized Blythe dolls for adoption. Connecting doll fans around the world."
meta_image: "cover.png" # should exist in `app/assets/images/`
